
package ru.atconsulting.bigdata.services.glassfish.crm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRMOperationsSOAPService", targetNamespace = "urn:gf-crmoperations:interface-soap", wsdlLocation = "http://ms-glass006:4466/CRMOperationsUrl?wsdl")
public class CRMOperationsSOAPService
    extends Service
{

    private final static URL CRMOPERATIONSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRMOPERATIONSSOAPSERVICE_EXCEPTION;
    private final static QName CRMOPERATIONSSOAPSERVICE_QNAME = new QName("urn:gf-crmoperations:interface-soap", "CRMOperationsSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ms-glass006:4466/CRMOperationsUrl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRMOPERATIONSSOAPSERVICE_WSDL_LOCATION = url;
        CRMOPERATIONSSOAPSERVICE_EXCEPTION = e;
    }

    public CRMOperationsSOAPService() {
        super(__getWsdlLocation(), CRMOPERATIONSSOAPSERVICE_QNAME);
    }

    public CRMOperationsSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRMOPERATIONSSOAPSERVICE_QNAME, features);
    }

    public CRMOperationsSOAPService(URL wsdlLocation) {
        super(wsdlLocation, CRMOPERATIONSSOAPSERVICE_QNAME);
    }

    public CRMOperationsSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRMOPERATIONSSOAPSERVICE_QNAME, features);
    }

    public CRMOperationsSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMOperationsSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModernCRMInterface
     */
    @WebEndpoint(name = "ModernCRMInterfaceBindingPort")
    public ModernCRMInterface getModernCRMInterfaceBindingPort() {
        return super.getPort(new QName("urn:gf-crmoperations:interface-soap", "ModernCRMInterfaceBindingPort"), ModernCRMInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModernCRMInterface
     */
    @WebEndpoint(name = "ModernCRMInterfaceBindingPort")
    public ModernCRMInterface getModernCRMInterfaceBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gf-crmoperations:interface-soap", "ModernCRMInterfaceBindingPort"), ModernCRMInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRMOPERATIONSSOAPSERVICE_EXCEPTION!= null) {
            throw CRMOPERATIONSSOAPSERVICE_EXCEPTION;
        }
        return CRMOPERATIONSSOAPSERVICE_WSDL_LOCATION;
    }

}
