
package ru.atconsulting.bigdata.services.glassfish.crm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "internalSystemErrorException", targetNamespace = "urn:gf-crmoperations:types")
public class InternalSystemErrorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InternalSystemErrorException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InternalSystemErrorException_Exception(String message, InternalSystemErrorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InternalSystemErrorException_Exception(String message, InternalSystemErrorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.atconsulting.bigdata.client.glassfish.crm.InternalSystemErrorException
     */
    public InternalSystemErrorException getFaultInfo() {
        return faultInfo;
    }

}
